services:
  pjn_postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_esgi_data:/var/lib/postgresql/data

  pjn_adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8080:8080"
    depends_on:
      - pjn_postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  pjn_app:
    container_name: my-app
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=mydatabase
      - DB_PASSWORD=admin
      - DB_USER=admin
      - DB_SYNCHRONISE=true
      - DB_HOST=pjn_postgres
      - JWT_SECRET=supersecret123
    depends_on:
      - pjn_postgres


volumes:
  postgres_esgi_data: